### ISSUE TITLE
Transp Otter fährt in Schleife vor und  zurück...

### ISSUE THREAD

**Issue by P-A-Trick** [lucysrausch/hoverboard-firmware-hack#179]
Hallo habe jetzt das zweite Hoverboard zerlegt und komme nicht weiter...?¡ Mein Transp Otter fährt eine Umdrehung vorwärts, stoppt, fährt eine Umdrehung rückwärts, stoppt und piept dann 5 mal. Dann fängt es wieder von vorne an.. Der Gametrak funktioniert nicht, obwohl Spannung 3.3V drauf liegt, kompiliert habe ich die lucysrauschenb Firmware mit dem online Compiler auf Pionierland.de, hat soweit auch alles super geklappt nun komme ich einfach nicht weiter und bitte um Hilfe. Vielen Dank  Greetz aus köln

**Comment by P-A-Trick** [comment]
Habe eine andere Firmware compiled, nun ist das Problem behoben!

**Comment by larsmm** [comment]
Hi, please have a look at the new project. This one is deprecated.
https://github.com/EFeru/hoverboard-firmware-hack-FOC
