### ISSUE TITLE
Extract one channel.

### ISSUE THREAD

**Issue by Kambodia91** [lucysrausch/hoverboard-firmware-hack#183]
hello, I have a hover board with two separate bldc control boards, I soldered stm32f103CBT6 48pin on them. Is it possible to extract the foc control for the bldc controller, e.g. via usart? The circuit is equipped with current measurement on two phases, voltage measurement and main current measurement. I also have a pinout of how the stm32 is connected
![STM32-Master](https://user-images.githubusercontent.com/88535933/210341420-6020f131-2aa5-4792-84c4-404df5921b73.jpg)
![STM32-Slave](https://user-images.githubusercontent.com/88535933/210341465-8cab66e3-6a5a-428e-8ac8-a3e2151423d9.jpg)
both boards are connected by usart0 PA2 and PA3.

**Comment by Candas1** [comment]
https://github.com/EFeru/hoverboard-firmware-hack-FOC

**Comment by Kambodia91** [comment]
I know about you. but this software is not compatible with my stm32 version. in platform.ini the stm32f103RC processor is declared, it is a processor with 64 pin outputs. I have stm32f103CB in 48pin outputs. Is there anyone who can extract the code for only one motor / controller? Regards.

**Comment by Kambodia91** [comment]
Model informatorom: https://github.com/EFeru/hoverboard-firmware-hack-FOC/issues/364
